### ISSUE TITLE
Background Music

### ISSUE THREAD

**Issue by Aethereux** [RedFlameKen2/Hiraya-Storybook#5]
The background music isn't playing when the page loads (probably needs to interact to play for pc. But for mobile devices idk yet)

**Comment by Aethereux** [comment]
- Should we make a button to play the audio instead of looping the music throughout?
- Some web browsers have restrictions on autoplaying media for user experience and security reasons. Autoplaying audio may not work unless the user interacts with the page first. Consider adding a play button or similar user interaction to trigger the audio playback.
-

**Comment by RedFlameKen2** [comment]
people are able to run web games without having to manually play audio. probably a javascript thing (always a javascript thing). i'll look into javascript stuff for playing audio.
